version: '3.5'

services:
  clementine_frontend:
    build:
      context: ./frontend/docker/development/nginx
    ports:
      - ${FRONTEND_NGINX_PORT}:80
    volumes:
      - ./frontend:/app

  clementine_database:
    container_name: clementine_database
    image: postgres:13-alpine
    volumes:
      - clementine_db_data:/pg-data
      - ./database/init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /pg-data
    networks:
      - clementine

  clementine_adminer:
    container_name: clementine_adminer
    build:
      context: ./
      dockerfile: DockerfileAdminer
    image: clementine/adminer:v1
    ports:
      - ${ADMINER_PORT}:8080
    networks:
      - clementine

  clementine_nginx:
    build:
      context: ./
      dockerfile: DockerfileNginx
    image: clementine/nginx:v1
    container_name: clementine_nginx
    volumes:
      - ./src/:/var/www/html/
      - ./nginx/logs/:/var/log/nginx/
    ports:
      - ${API_NGINX_PORT}:443
    networks:
      clementine:
        aliases:
          - api.loc-sol-workspace.docker

  clementine_php:
    build:
      context: ./
      dockerfile: DockerfilePHP
    image: clementine/php:v1
    container_name: clementine_php
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP}
    volumes:
      - ./src/:/var/www/html
      - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - clementine

  clementine_php_cli:
    build:
      context: ./
      dockerfile: DockerfilePHPCli
    image: clementine/php_cli:v1
    container_name: clementine_php_cli
    volumes:
      - ./src/:/var/www/html/
    networks:
      - clementine

  clementine_redis:
    container_name: clementine_redis
    image: redis:5-alpine
    networks:
      - clementine

  clementine_redis_commander:
    container_name: clementine_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:clementine_redis:6379
    ports:
      - "${REDIS_COMMANDER_PORT}:8081"
    networks:
      - clementine

volumes:
  clementine_db_data:

networks:
  clementine: 
    external: false
    name: clementine
