version: '3.5'

services:
  clementine_frontend_nginx:
    build:
      context: ./frontend/docker/development/nginx
    container_name: clementine_frontend_nginx
    ports:
      - ${FRONTEND_NGINX_PORT}:80
    volumes:
      - ./frontend:/app

  clementine_api_nginx:
    build:
      context: ./api/docker/development/nginx
    container_name: clementine_api_nginx
    volumes:
      - ./api:/app
    ports:
      - ${API_NGINX_PORT}:443
    networks:
      clementine:
        aliases:
          - api.clementine.docker

  clementine_database:
    container_name: clementine_database
    image: postgres:13-alpine
    volumes:
      - clementine_db_data:/pg-data
      - ./api/docker/development/postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      PGDATA: /pg-data
    ports:
      - ${POSTGRESQL_PORT}:5432
    networks:
      - clementine

  clementine_php:
    build:
      context: ./api/docker/development/php-fpm
    container_name: clementine_php
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP}
    volumes:
      - ./api:/app
    networks:
      - clementine

  clementine_php_cli:
    build:
      context: ./api/docker/development/php-cli
    container_name: clementine_php_cli
    volumes:
      - ./api:/app
    networks:
      - clementine

  clementine_redis:
    container_name: clementine_redis
    image: redis:5-alpine
    networks:
      - clementine

volumes:
  clementine_db_data:

networks:
  clementine: 
    external: false
    name: clementine
